"""empty message

Revision ID: 081a8ccd1989
Revises: 17ee141d23b7
Create Date: 2021-11-30 18:03:43.673146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081a8ccd1989'
down_revision = '17ee141d23b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bank_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('bank_account_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bank_account_no')
    op.drop_column('user', 'bank_name')
    # ### end Alembic commands ###
