"""empty message

Revision ID: 2c1479311acb
Revises: 2da70e320bf2
Create Date: 2021-11-29 15:28:59.238738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1479311acb'
down_revision = '2da70e320bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('at_rate', sa.Integer(), nullable=False))
    op.drop_column('card', 'rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('card', 'at_rate')
    # ### end Alembic commands ###
