"""empty message

Revision ID: 5aadf6bd0f99
Revises: 6000b1d5a061
Create Date: 2021-11-30 20:26:28.227813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aadf6bd0f99'
down_revision = '6000b1d5a061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bank_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('bank_account_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bank_account_no')
    op.drop_column('user', 'bank_name')
    # ### end Alembic commands ###
