"""empty message

Revision ID: 81a75f882d7f
Revises: 849def24bf6c
Create Date: 2021-12-01 10:59:17.624867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a75f882d7f'
down_revision = '849def24bf6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdrawal', sa.Column('status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdrawal', 'status')
    # ### end Alembic commands ###
