"""empty message

Revision ID: a3052bfa2c5c
Revises: 1f843d291a4e
Create Date: 2021-11-29 17:04:48.158436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3052bfa2c5c'
down_revision = '1f843d291a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'status')
    # ### end Alembic commands ###
