"""empty message

Revision ID: c6dd698a609e
Revises: d295fe0fd3bf
Create Date: 2021-11-29 16:58:58.749705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6dd698a609e'
down_revision = 'd295fe0fd3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('card', 'state',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'state',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('card', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
