"""empty message

Revision ID: c7dc225af22a
Revises: c6dd698a609e
Create Date: 2021-11-29 17:00:40.877525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7dc225af22a'
down_revision = 'c6dd698a609e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('card', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('state', sa.String(), autoincrement=False, nullable=True))
    op.alter_column('card', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
