"""empty message

Revision ID: d295fe0fd3bf
Revises: 2c1479311acb
Create Date: 2021-11-29 16:00:40.941763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd295fe0fd3bf'
down_revision = '2c1479311acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('state', sa.String(length=30), nullable=False))
    op.alter_column('card', 'note',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('card', 'state')
    # ### end Alembic commands ###
